image_root: 'images/CUHK-PEDES/imgs'
test_file: 'data/finetune/cuhk_test.json'
val_file: 'data/finetune/cuhk_val.json'
train_file:  ['data/finetune/cuhk_train.json']

region: 0


## Vision Encoder
vision_config: 'configs/config_swinB_384x256.json'
window_size: 8
patch_size: 32
image_res: 384
h: 384
w: 256


## Text Encoder
text_config: 'configs/config_bert.json'
text_encoder: 'data/bert-base-uncased'


## Training
load_pretrained: True
load_params: False

lr_2: True

embed_dim: 2048
itc_dop: 0.5
LabelSmooth: 0.2
temp: 0.07

max_tokens: 56
max_words: 56
icfg_rstp: False
eda: True
erasing_p: 0.6

## mlm loss
mask_prob: 0.25
max_masks: 10
skipgram_prb: 0.2
skipgram_size: 3
mask_whole_word: True

batch_size_train: 40


## test
batch_size_test: 40
batch_size_test_text: 200
k_test: 512

test_hflip: True


## Other Settings
optimizer: {opt: adamW, lr: 1e-4, weight_decay: 0.01, lr_mult: 2, lr_x: 2}
schedular: {sched: step, lr: 1e-4, epochs: 30, num_warmup_steps: 0.1}
